# 开发环境
online: false       # 线上才验证登录

server:
  port: 10200

logging.config: classpath:log-test.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
#        include: bus-refresh
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
    application:
      name: applets-service
    cache:
      type: redis
    session:
      store-type: redis
    redis:
      host: 192.168.1.201
      port: 6379
      password:

tls:
  sdkAppid: 1400102354
  private-key: D:\applets\src\main\key\private_key
  public-key: D:\applets\src\main\key\public_key
  admin-Account: xyb123456
#  private-key: /home/chen/key/private_key
#  public-key: /home/chen/key/public_key

db:
    ai:
        url: jdbc:mysql://192.168.1.123:3306/ai?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.xyb.common.util.ShowSqlInterceptor
        username: xyb
        password: payadd.cn

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

    xyb:
        url: jdbc:mysql://192.168.1.123:3306/xyb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.xyb.common.util.ShowSqlInterceptor
        username: xyb
        password: payadd.cn
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

