# 生产环境
#online: true       # 线上才验证登录
online: false       #

server:
  port: 10201

logging.config: classpath:log-prod.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
#        include: bus-refresh
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
    application:
      name: shop-service
    cache:
      type: redis
    session:
      store-type: redis
    redis:
      host: 10.29.250.192
      port: 6379
      password:

tls:
  sdkAppid: 1400102354
  admin-Account: xyb123456
  private-key: /home/xyb/apps/appetls/key/private_key
  public-key: /home/xyb/apps/applets/key/public_key

db:
    ai:
        url: jdbc:mysql://rm-wz9r3s14fj3vd28s6.mysql.rds.aliyuncs.com:3306/ai?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.xyb.common.util.ShowSqlInterceptor
        username: xyb
        password: xyb@2016

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

    xyb:
        url: jdbc:mysql://rm-wz9r3s14fj3vd28s6.mysql.rds.aliyuncs.com:3306/xyb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.xyb.common.util.ShowSqlInterceptor
        username: xyb
        password: xyb@2016
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
