logging.config: classpath:log-prod.xml

server:
   port: 10100
spring:
   application:
      name: gateway-service
   sleuth:
      sampler:
          probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
   zipkin:
      base-url: http://192.168.1.201:9411 # 指定了 Zipkin 服务器的地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
# 上传大文件得将超时时间设置长一些，否则会报超时异常。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
#  routes:
#        user-service:
#            path: /userapi/**
#            url: http://localhost:8762