hello: my test!

server:
  port: 8986

spring:
  application:
    name: config-client-service
  rabbitmq:
    host: 192.168.1.202
    port: 5672
    username: admin
    password: admin
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: bus-refresh